[package]
name = "stdb_explorer"
version = "2025.8.22"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
spacetimedb-sdk = "1.3.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
